"""empty message

Revision ID: 177428e67ff2
Revises: 620164be59c9
Create Date: 2023-11-01 23:58:11.950605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177428e67ff2'
down_revision = '620164be59c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('state', sa.String(length=80), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('county', sa.String(length=80), nullable=False),
    sa.Column('full_address', sa.String(length=80), nullable=False),
    sa.Column('details', sa.String(length=80), nullable=False),
    sa.Column('zipcode', sa.String(length=80), nullable=False),
    sa.Column('latitude', sa.String(length=80), nullable=False),
    sa.Column('longitude', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('address')
    # ### end Alembic commands ###
