"""empty message

Revision ID: 4c570535ef8e
Revises: b162a9543b98
Create Date: 2023-11-18 02:19:32.795408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c570535ef8e'
down_revision = 'b162a9543b98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offerer_services', schema=None) as batch_op:
        batch_op.drop_constraint('offerer_services_status_key', type_='unique')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('evaluating_proposal', 'task_done', 'task_not_done', name='petitionerstatus'),
               type_=sa.String(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=80),
               type_=postgresql.ENUM('evaluating_proposal', 'task_done', 'task_not_done', name='petitionerstatus'),
               existing_nullable=False)

    with op.batch_alter_table('offerer_services', schema=None) as batch_op:
        batch_op.create_unique_constraint('offerer_services_status_key', ['status'])

    # ### end Alembic commands ###
