"""empty message

Revision ID: 64c91f70b0d2
Revises: 5bf4dcf9fce2
Create Date: 2023-11-28 01:22:46.253759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64c91f70b0d2'
down_revision = '5bf4dcf9fce2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=80), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_column('country')

    # ### end Alembic commands ###
