"""empty message

Revision ID: 85d08760d3c2
Revises: 276f350f9fca
Create Date: 2023-11-12 13:54:31.636824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85d08760d3c2'
down_revision = '276f350f9fca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petitioner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('petitioner', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
