"""empty message

Revision ID: 99dbda8d2ab2
Revises: ff9d0c82e384
Create Date: 2023-11-08 23:30:02.690221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99dbda8d2ab2'
down_revision = 'ff9d0c82e384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.alter_column('details',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.alter_column('longitude',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('details',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    # ### end Alembic commands ###
