"""empty message

Revision ID: b162a9543b98
Revises: b37aae544e90
Create Date: 2023-11-18 02:10:01.811083

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b162a9543b98'
down_revision = 'b37aae544e90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offerer_services', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('pending_approval', 'accepted', 'insuficient', 'done', name='offererstatus'),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['status'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offerer_services', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('status',
               existing_type=sa.String(length=80),
               type_=postgresql.ENUM('pending_approval', 'accepted', 'insuficient', 'done', name='offererstatus'),
               existing_nullable=False)

    # ### end Alembic commands ###
